### ISSUE TITLE
can't Access Dataset

### ISSUE THREAD

**Issue by Yurikusu** [shenyangHuang/TGB#101]
Hello I am pretty new to GNN and I want to try out the Models on TGB and I am already failing at the very start.

With the following code i was expecting to get access to the dataset but it seems not to work:

from tgb.linkproppred.dataset_pyg import PyGLinkPropPredDataset

DATA = "tgbl-review"
dataset = PyGLinkPropPredDataset(name=DATA, root="datasets")

when I try to access it through postman I get a 503 error:

<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

**Comment by shenyangHuang** [comment]
Hi Yurikusu, 

Thanks for your interest in our work and sharing your issue. 
There might have been some server issue when you access it. 
The dataset can be downloaded manually from [here](https://object-arbutus.cloud.computecanada.ca/tgb/tgbl-review-v2.zip). 
In general, you can find all the download links in [`info.py`](https://github.com/shenyangHuang/TGB/blob/main/tgb/utils/info.py)

```
Dataset tgbl-review version 2 not found.
Please download the latest version of the dataset.
Will you download the dataset(s) now? (y/N)
```

When you run the code, you should be able to see the above text in your command prompt and you need to enter `y` to proceed to download the dataset. 

Can you let me know if this fixes the error for you? 

Best,
Andy

**Comment by Yurikusu** [comment]
It seems everything works fine now!
It was just a server error for me then. I didn't change my code and now it works :)
