### ISSUE TITLE
Missing of eval_set and issues of edge feature

### ISSUE THREAD

**Issue by yule-BUAA** [shenyangHuang/TGB#47]
Hi,

Thanks for this great repository!

But when I ran the code on the `tgbl-wiki` dataset, I found some issues.

1. It seems that the `eval_set ` of `NegativeEdgeSampler` in `tgb/linkproppred/negative_sampler.py` is missing. The pkl file that contains negative edge samples for evaluation is unavailable.
2. The edge features of `dataset.edge_feat` and `dataset.full_data['edge_feat']` are inconsistent. See the following example.

```
from tgb.linkproppred.dataset import LinkPropPredDataset
import numpy as np

dataset = LinkPropPredDataset(name='tgbl-wiki', root="datasets", preprocess=True)

print("dataset.edge_feat:")
print(dataset.edge_feat)

print("dataset.full_data['edge_feat']:")
print(dataset.full_data['edge_feat'])

minus = dataset.edge_feat - dataset.full_data['edge_feat']
print("dataset.edge_feat - dataset.full_data['edge_feat']:")
print(minus)
print("minus all equal to one:")
print(np.isclose(minus, np.ones(minus.shape)).all())
```
The execution results are:
```
dataset.edge_feat:
[[0.82493749 0.82332236 0.06290923 ... 0.94953617 0.95855204 0.96122518]
 [0.82493749 0.82332236 0.06290923 ... 0.94953617 0.95855204 0.96122518]
 [0.82493749 0.82332236 0.06290923 ... 0.94953617 0.95855204 0.96122518]
 ...
 [1.27344377 1.30081117 2.12243376 ... 0.94953617 0.95855204 0.96122518]
 [0.82493749 0.82332236 0.06290923 ... 0.94953617 0.95855204 0.96122518]
 [0.82493749 0.82332236 0.06290923 ... 0.94953617 0.95855204 0.96122518]]
dataset.full_data['edge_feat']:
[[-0.17506251 -0.17667764 -0.93709077 ... -0.05046383 -0.04144796
  -0.03877482]
 [-0.17506251 -0.17667764 -0.93709077 ... -0.05046383 -0.04144796
  -0.03877482]
 [-0.17506251 -0.17667764 -0.93709077 ... -0.05046383 -0.04144796
  -0.03877482]
 ...
 [ 0.27344377  0.30081117  1.12243376 ... -0.05046383 -0.04144796
  -0.03877482]
 [-0.17506251 -0.17667764 -0.93709077 ... -0.05046383 -0.04144796
  -0.03877482]
 [-0.17506251 -0.17667764 -0.93709077 ... -0.05046383 -0.04144796
  -0.03877482]]
dataset.edge_feat - dataset.full_data['edge_feat']:
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
minus all equal to one:
True
```

It would be very nice of you to address these issues!

Best wishes,

Le Yu

**Comment by shenyangHuang** [comment]
Hi Le, 
Thanks for your comments and interest in our work!
 
**for point 1** , the pkl files are different for each linkproppred dataset thus it is downloaded automatically with the dataset download, it should be in folder `tgb/datasets/tgbl-wiki` once you downloaded the dataset. You can also download from this [link](https://object-arbutus.cloud.computecanada.ca/tgb/tgbl-wiki.zip) manually (for all dataset links see [`info.py`](https://github.com/shenyangHuang/TGB/blob/main/tgb/utils/info.py) ). 
Once you downloaded the zip, you should be able to find 
- `tgbl-wiki_edgelist.csv`
- `tgbl-wiki_test_ns.pkl`
-  `tgbl-wiki_val_ns.pkl`
the ns.pkl files stores the negative samples and they are queried by the negative sampler at run time. 
you can find example on how to use it in [`examples/linkproppred/tgbl-review`](https://github.com/shenyangHuang/TGB/tree/main/examples/linkproppred/tgbl-wiki)

**for point 2**, thanks for pointing it out, I will look into it this week.

**Comment by shenyangHuang** [comment]
Hi Le, 

for issue 2, it is now fixed in PR #48

**Comment by yule-BUAA** [comment]
Thanks for your timely reply! 
I will try it later.  ^_^

**Comment by shenyangHuang** [comment]
Thanks, I have merged the PR into the `main` branch, let me know if you still encounters any issues
