### ISSUE TITLE
A question about the find_next_labels_batch function

### ISSUE THREAD

**Issue by yule-BUAA** [shenyangHuang/TGB#49]
Hello Huang,

I have a question about the `find_next_labels_batch` function in `tgb.nodeproppred.dataset`. Why should we use `if self.label_ts_idx >= (self.label_ts.shape[0] - 1)` instead of` if self.label_ts_idx > (self.label_ts.shape[0] - 1)` [here](https://github.com/shenyangHuang/TGB/blob/c0ed96262306775f620d4c13272b68e50608e31c/tgb/nodeproppred/dataset.py#L305)? It seems that using **>=** would skip the node labels in the last year in the dataset.

Looking forward to your reply!

Best wishes,
Le Yu

**Comment by yule-BUAA** [comment]
Moreover, I find that the numbers of nodes and edges are **mismatched** with the reported number in the paper.
When I ran the following code
```
from tgb.nodeproppred.dataset_pyg import PyGNodePropPredDataset

for dataset_name in ["tgbn-trade", "tgbn-genre", "tgbn-reddit"]:
    dataset = PyGNodePropPredDataset(name=dataset_name, root="datasets")
    data = dataset.dataset.full_data
      
    src_node_ids = data['sources'].astype(np.longlong)
    dst_node_ids = data['destinations'].astype(np.longlong)
    edge_raw_features = data['edge_feat'].astype(np.float64)
      

    num_edges = edge_raw_features.shape[0]
    print("actual edge number: ", num_edges)
    print("reported edge number: ", data_num_edges_map[dataset_name])
      
    num_nodes = len(set(src_node_ids) | set(dst_node_ids))
    print("actual node number: ", num_nodes)
    print("reported node number: ", data_num_nodes_map[dataset_name])
```
I got the results:
tgbn-trade

```
actual edge number:  468245
reported edge number:  507497
actual node number:  255
reported node number:  255
```
tgbn-genre

```
actual edge number:  17858395
reported edge number:  17858395
actual node number:  1505
reported node number:  992
```
tgbn-reddit

```
actual edge number:  27174118
reported edge number:  27174118
actual node number:  11766
reported node number:  11068
```

Could you help me point out the reason? Thanks a lot!

**Comment by shenyangHuang** [comment]
Thanks for raising this issue, Le, I will take a look next week

**Comment by shenyangHuang** [comment]
> Why should we use if self.label_ts_idx >= (self.label_ts.shape[0] - 1) instead of if self.label_ts_idx > (self.label_ts.shape[0] - 1)

Hi Le, thanks for checking the code carefully and your interest in our work! 
This is indeed an off by one error, will be fixed in `main` soon

**Comment by shenyangHuang** [comment]
> `tgbn-genre` and `tgbn-reddit` the number of nodes are inconsistent. Could you help me point out the reason? Thanks a lot!
For these datasets, we listed the number of users as they are the nodes that have labels. These are bipartite graphs, in `tgbn-genre` for example, 992 nodes are users while the rest for music genres.
