### ISSUE TITLE
Running codes from examples with much lower performances

### ISSUE THREAD

**Issue by yeahjack** [shenyangHuang/TGB#50]
Dear Developers,

Firstly, I am expressing my sincere appreciation for your excellent work in temporal graph learning. It is such a great pleasure to learn and grow from your project.

Recently, I have been working with the code from the examples folder. Specifically, I have been using TGB/examples/nodeproppred/tgbn-trade/tgn.py. I attempted to run the code without modifying any hyperparameters, expecting to produce results similar to those reported in the leaderboard.

Unfortunately, the performance I observed was notably lower than anticipated. Specifically, my Normalized Discounted Cumulative Gain (NDCG) score was only 10% of the score reported in the leaderboard. I'm confident that I followed the instructions and ran the code correctly.

Given this, could any potential issues might have led to such a discrepancy in the NDCG score? Are there any specific configurations or settings I might need to look into? Any guidance to help improve my model's performance would be greatly appreciated.

Thank you very much for your time and assistance. I am excited to hear from you soon.

**Comment by shenyangHuang** [comment]
Hi,

Thanks for reporting this issue and your interest in our work!
Can you record the exact number you are getting here? 
On the leaderboard, the `tgbn-trade` score is reported in percentage for better readability, see the Table header [here](https://tgb.complexdatalab.com/docs/leader_nodeprop/#tgbn-trade).
Thus, the reported number would appear larger as it shows percentage. 
For example, when I run `moving_average` from my laptop just now, I got `0.0037111683311804116` which is consistent with the 0.371 % reported on the website. 
Hope it clarifies.

**Comment by shenyangHuang** [comment]
Thanks for checking the results carefully and your interest in our work !
