### ISSUE TITLE
Are MRR numbers reported in your paper correct?

### ISSUE THREAD

**Issue by OlegPlatonov** [shenyangHuang/TGB#59]
Hi! I wonder if the bug in rank computation reported in #55 affected the results of different models that you report in your paper. At first I thought that it did not, as you probably used pytorch tensors for evaluation, and the bug only affected numpy arrays, which is why I did not mention it in the original issue. However, now I see that the function _parse_and_check_input in the Evaluator class converts all inputs to numpy arrays (which seems unnecessary, as the function _eval_hits_and_mrr supports both numpy arrays and pytorch tensors). As far as I understand, this means that your examples use numpy arrays for evaluation and thus were affected by the bug in rank computation, which means that the metrics reported in your paper are incorrect.

**Comment by yule-BUAA** [comment]
Hello,
I have conducted [some experiments](https://github.com/yule-BUAA/DyGLib_TGB) on TGB including the mentioned link property prediction task. In my opinion, the missing `axis=1` argument will affect the results when we compute metrics on a batch of data. However, in the evaluation process of TGB, the positive links are evaluated one by one. See [here](https://github.com/shenyangHuang/TGB/blob/20ac5f0374497bd6ffa34da04a87daaad8b0e474/examples/linkproppred/tgbl-wiki/tgn.py#L140) for an example. In such a case, the batch size is equal to 1, making `sum()` and `sum(axis=1)` provide the same results. Note that the additional dimension of results kept by `sum(axis=1)` will be discarded in computing the final average metrics via `mean()` operation (see [here](https://github.com/shenyangHuang/TGB/blob/20ac5f0374497bd6ffa34da04a87daaad8b0e474/examples/linkproppred/tgbl-wiki/tgn.py#L178)). Therefore, the metrics are computed correctly.

I hope this will address your issue. Moreover, it would be quite helpful if the TGB authors could clarify the shape of inputs in the evaluation functions or make their code annotations more comprehensive.

**Comment by fpour** [comment]
Thanks again for pointing out this issue. 
As @yule-BUAA mentioned, here we don't get different results because we calculate MRR for each positive edge vs. its corresponding negative edges, and then averaged over all positive edges. 
Anyway, for eliminating any further issue, we added the default setting in the updated code.
And thanks for the suggestion, we will add more clarifying comments and hints to the code.
