### ISSUE TITLE
Scripts for generating _val_ns.pkl and _test_ns.pkl

### ISSUE THREAD

**Issue by ChatterjeeAyan** [shenyangHuang/TGB#63]
Hi,

I am experimenting with TGB for different negatives. The _val_ns.pkl and _test_ns.pkl files are downloaded automatically in TGB. Is there a script that generates these files? 

Thanks,
Ayan

**Comment by shenyangHuang** [comment]
Hi Ayan, 

Thanks for your interest in our work.  The negative samples are generated based on [`tgx/linkproppred/negative_generator.py`](https://github.com/shenyangHuang/TGB/blob/main/tgb/linkproppred/negative_generator.py) where you can find the functions for generating both historical and random negative edges. 

To see one example for how we generated it, check [`tgb/datasets/dataset_scripts/tgbl-comment_neg_generator.py`
](https://github.com/shenyangHuang/TGB/blob/main/tgb/datasets/dataset_scripts/tgbl-comment_neg_generator.py)
Hope it answers your question. 

Best,
Shenyang(Andy) Huang
