### ISSUE TITLE
GPU Acceleration

### ISSUE THREAD

**Issue by ChatterjeeAyan** [shenyangHuang/TGB#69]
I tried running tgbl-comment with and without GPU support. In both cases, each epoch takes around 10-12 hours. In the case of GPU support, the CUDA device is T4/A100 (the GPU used in the instance). Does TGB support GPU acceleration? What's the expected time for each epoch in tgbl-comment?

**Comment by shenyangHuang** [comment]
Hi Ayan, 

Thanks for your interest in our work. GPU acceleration is indeed supported in the examples for TGB. 
The accelerator is set automatically with `device = torch.device("cuda" if torch.cuda.is_available() else "cpu")`  and all examples uses GPU where enabled. 
The run time for each epoch in `tgbl-comment` should be around a few hours (and not be at the 10-12 hours range). Compute resources and setup can be found in appendix E of [the paper](https://openreview.net/forum?id=qG7IkQ7IBO)
Have a nice day. 

Best,
Andy
