### ISSUE TITLE
Typo on TGB website

### ISSUE THREAD

**Issue by e-izdfr** [shenyangHuang/TGB#78]
Hello. In the _tgbn-token_ dataset part on [TGB website](https://tgb.complexdatalab.com/docs/nodeprop/), _tgbn-reddit_ should be changed to  _tgbn-token_ .

![Screenshot 2024-02-19 211158](https://github.com/shenyangHuang/TGB/assets/81484391/55d77bab-01b8-4104-b706-967e3a4fd654)

**Comment by shenyangHuang** [comment]
Hi, 

Thanks for reporting this, it has been updated on the website. 

Best,
Andy

**Comment by e-izdfr** [comment]
I see sir. You're welcome!
