### ISSUE TITLE
[QST] How the message of TGN is computed

### ISSUE THREAD

**Issue by cctry** [shenyangHuang/TGB#80]
Hello,

I need clarification about the [implementation](https://github.com/shenyangHuang/TGB/blob/c1178e3f107844d367dfa04337d48a24731952af/modules/memory_module.py#L156) of TGN memory.
```
        # Compute messages (src -> dst).
        msg_s, t_s, src_s, dst_s = self._compute_msg(
            n_id, self.msg_s_store, self.msg_s_module
        )
```
The TGN message should be the concat of src mem, dst_mem, t, and raw_msg. How does this code implement this?

**Comment by shenyangHuang** [comment]
Hi, 

Thanks for asking, the self._compute_msg() function is defined in [TGB/modules/memory_modules.py](https://github.com/shenyangHuang/TGB/blob/c1178e3f107844d367dfa04337d48a24731952af/modules/memory_module.py#L156) as follows:

```
def _compute_msg(
        self, n_id: Tensor, msg_store: TGNMessageStoreType, msg_module: Callable
    ):
        data = [msg_store[i] for i in n_id.tolist()]
        src, dst, t, raw_msg = list(zip(*data))
        src = torch.cat(src, dim=0)
        dst = torch.cat(dst, dim=0)
        t = torch.cat(t, dim=0)
        raw_msg = torch.cat(raw_msg, dim=0)
        t_rel = t - self.last_update[src]
        t_enc = self.time_enc(t_rel.to(raw_msg.dtype))

        msg = msg_module(self.memory[src], self.memory[dst], raw_msg, t_enc)

        return msg, t, src, dst
```

You can also reference it from the [original TGN implementation in PyG](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/models/tgn.html).

Best,
Andy

**Comment by shenyangHuang** [comment]
closing comment due to inactivity

**Comment by shenyangHuang** [comment]
closing comment due to inactivity
