### ISSUE TITLE
Model weights and optimizer state not reset between runs

### ISSUE THREAD

**Issue by databaaz** [shenyangHuang/TGB#88]
In [`examples/linkproppred`](https://github.com/shenyangHuang/TGB/tree/main/examples/linkproppred), the models carry forward their optimal weights from one run to the next.
`reset_parameters()` need to be called on the learnable modules of the model i.e. `memory`, `gnn` and `link_pred` in case of `tgn`.
Similarly, the optimizer needs to be reinitialized at the beginning of each run.

**Comment by shenyangHuang** [comment]
Thanks for this point Shahbaz, in the paper we actually didn't use `num_runs` to run repeated trials (we do single runs (`num_runs=1` and just explicitly set the single seed). Thus we didn't encounter this issue before. Yeah, we should update the script to reset the model weight etc.

Best,
Andy

**Comment by shenyangHuang** [comment]
this is addressed in PR #94
