### ISSUE TITLE
What is the implementation of GraphMixer

### ISSUE THREAD

**Issue by lxd99** [shenyangHuang/TGB#97]
Hi, thanks for your great work! I noticed that the implementation of GraphMixer isn't available in the modules directory of the TGB repository. Could you please share how the TGB team implemented GraphMixer for the results reported on the [Leaderboards for Dynamic Link Property Prediction](https://tgb.complexdatalab.com/docs/leader_linkprop/)? Did you use the official implementation or reimplement it yourselves?

**Comment by shenyangHuang** [comment]
Hi,

Thanks for your question. 
We used adapted the implementation here: https://github.com/fpour/TGB_Baselines

Best,
Andy

**Comment by shenyangHuang** [comment]
closing this issue as it is resolved.
